"""add org_unit_id to score_snapshot, make app_id and scan_run_id nullable

Revision ID: 0d4a7d325fe1
Revises: f49e037fdb6e
Create Date: 2026-04-10 14:28:29.587060

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d4a7d325fe1"
down_revision: str | Sequence[str] | None = "f49e037fdb6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("score_snapshot", sa.Column("org_unit_id", sa.BigInteger(), nullable=True))
    op.alter_column("score_snapshot", "app_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("score_snapshot", "scan_run_id", existing_type=sa.BIGINT(), nullable=True)
    op.create_index("ix_score_snapshot_org_unit_id", "score_snapshot", ["org_unit_id"], unique=False)
    op.create_foreign_key(
        "fk_score_snapshot_org_unit_id", "score_snapshot", "org_unit", ["org_unit_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_score_snapshot_org_unit_id", "score_snapshot", type_="foreignkey")
    op.drop_index("ix_score_snapshot_org_unit_id", table_name="score_snapshot")
    op.alter_column("score_snapshot", "scan_run_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("score_snapshot", "app_id", existing_type=sa.BIGINT(), nullable=False)
    op.drop_column("score_snapshot", "org_unit_id")
    # ### end Alembic commands ###
