"""add on delete restrict to org_unit parent_id

Revision ID: 2256615e462f
Revises: dc4ced6bb712
Create Date: 2026-04-09 02:41:52.080926

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2256615e462f"
down_revision: str | Sequence[str] | None = "dc4ced6bb712"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("org_unit_parent_id_fkey"), "org_unit", type_="foreignkey")
    op.create_foreign_key("fk_org_unit_parent_id", "org_unit", "org_unit", ["parent_id"], ["id"], ondelete="RESTRICT")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_org_unit_parent_id", "org_unit", type_="foreignkey")
    op.create_foreign_key("org_unit_parent_id_fkey", "org_unit", "org_unit", ["parent_id"], ["id"])
    # ### end Alembic commands ###
