"""add GIN index on rule_finding classifications

Revision ID: 4f287365ba40
Revises: 5837b201d00d
Create Date: 2026-04-12 12:23:15.132841

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f287365ba40"
down_revision: str | Sequence[str] | None = "5837b201d00d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_rule_finding_classifications", "rule_finding", ["classifications"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rule_finding_classifications", table_name="rule_finding", postgresql_using="gin")
    # ### end Alembic commands ###
