"""replace wcag_criterion text with wcag_criteria jsonb array

Revision ID: 5837b201d00d
Revises: cc5e604269d9
Create Date: 2026-04-12 12:03:40.447805

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5837b201d00d"
down_revision: str | Sequence[str] | None = "cc5e604269d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rule_finding",
        sa.Column(
            "wcag_criteria",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )

    # Backfill: extract all WCAG criterion tags (e.g. "wcag143" → "1.4.3") from tags JSONB array
    op.execute(
        sa.text("""
        UPDATE rule_finding
        SET wcag_criteria = (
            SELECT COALESCE(jsonb_agg(
                SUBSTRING(tag FROM 5 FOR 1) || '.' ||
                SUBSTRING(tag FROM 6 FOR 1) || '.' ||
                SUBSTRING(tag FROM 7)
            ), '[]'::jsonb)
            FROM jsonb_array_elements_text(tags) AS tag
            WHERE tag ~ '^wcag\\d\\d\\d+$'
        )
    """)
    )

    op.drop_column("rule_finding", "wcag_criterion")
    op.create_index("ix_rule_finding_wcag_criteria", "rule_finding", ["wcag_criteria"], postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DROP INDEX IF EXISTS ix_rule_finding_wcag_criteria"))
    op.add_column("rule_finding", sa.Column("wcag_criterion", sa.TEXT(), autoincrement=False, nullable=True))

    # Backfill: take first element from wcag_criteria array
    op.execute(
        sa.text("""
        UPDATE rule_finding
        SET wcag_criterion = wcag_criteria ->> 0
        WHERE jsonb_array_length(wcag_criteria) > 0
    """)
    )

    op.drop_column("rule_finding", "wcag_criteria")
    # ### end Alembic commands ###
