"""add app table

Revision ID: 8dade5d8f0e3
Revises: 2256615e462f
Create Date: 2026-04-09 12:28:15.904375

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8dade5d8f0e3"
down_revision: str | Sequence[str] | None = "2256615e462f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Fix org_unit PK/FK type: original migration used UUID, model now uses BIGINT.
    # UUID cannot auto-cast to BIGINT, so use raw SQL with USING clauses.
    op.drop_constraint("fk_org_unit_parent_id", "org_unit", type_="foreignkey")
    op.execute(sa.text("ALTER TABLE org_unit ALTER COLUMN parent_id TYPE BIGINT USING NULL"))
    op.execute(sa.text("ALTER TABLE org_unit ALTER COLUMN id TYPE BIGINT USING NULL"))
    op.execute(sa.text("TRUNCATE TABLE org_unit"))
    op.execute(sa.text("ALTER TABLE org_unit ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY"))
    op.create_foreign_key("fk_org_unit_parent_id", "org_unit", "org_unit", ["parent_id"], ["id"], ondelete="RESTRICT")
    # Add app table
    op.create_table(
        "app",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column(
            "brand", sa.Enum("Humana", "CenterWell", "Go365", "CarePlus", "Reliance", name="brand_type"), nullable=False
        ),
        sa.Column("org_unit_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("LENGTH(name) <= 255", name="ck_app_name_length"),
        sa.CheckConstraint("LENGTH(slug) <= 255", name="ck_app_slug_length"),
        sa.ForeignKeyConstraint(["org_unit_id"], ["org_unit.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_app_slug"),
    )
    op.create_index("ix_app_org_unit_id", "app", ["org_unit_id"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop app table first (FK depends on org_unit.id)
    op.drop_index("ix_app_org_unit_id", table_name="app")
    op.drop_table("app")
    sa.Enum(name="brand_type").drop(op.get_bind())
    # Revert org_unit PK/FK type back to UUID
    op.drop_constraint("fk_org_unit_parent_id", "org_unit", type_="foreignkey")
    op.execute(sa.text("ALTER TABLE org_unit ALTER COLUMN id DROP IDENTITY"))
    op.execute(sa.text("TRUNCATE TABLE org_unit"))
    op.execute(sa.text("ALTER TABLE org_unit ALTER COLUMN id TYPE UUID USING gen_random_uuid()"))
    op.execute(sa.text("ALTER TABLE org_unit ALTER COLUMN parent_id TYPE UUID USING NULL"))
    op.create_foreign_key("fk_org_unit_parent_id", "org_unit", "org_unit", ["parent_id"], ["id"], ondelete="RESTRICT")
    # ### end Alembic commands ###
