"""add single-root org unit index

Revision ID: 8fe96135b4ba
Revises: 48770eba4885
Create Date: 2026-07-11 19:19:55.434504

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8fe96135b4ba"
down_revision: str | Sequence[str] | None = "48770eba4885"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Guarded rollout (ADR 0026): existing data may predate the single-root
    # invariant. Abort with the offending rows rather than failing on index
    # creation or reparenting anything implicitly.
    conn = op.get_bind()
    root_ids = conn.execute(sa.text("SELECT id FROM org_unit WHERE parent_id IS NULL ORDER BY id")).scalars().all()
    if len(root_ids) > 1:
        raise RuntimeError(
            f"Cannot enforce the single-root org unit invariant: found {len(root_ids)} "
            f"parentless org units (ids {list(root_ids)}). Reparent all but one "
            "(PATCH /api/v1/org-units/{id} with the surviving root as parent_id), then re-run."
        )
    op.create_index(
        "uq_org_unit_single_root",
        "org_unit",
        [sa.literal_column("(parent_id IS NULL)")],
        unique=True,
        postgresql_where=sa.text("parent_id IS NULL"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_org_unit_single_root", table_name="org_unit", postgresql_where=sa.text("parent_id IS NULL"))
    # ### end Alembic commands ###
