"""replace single-column FK indexes with composites for hot read paths

Revision ID: c31f27959a81
Revises: 3737c72ff7ef
Create Date: 2026-04-26 12:13:00.285974

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c31f27959a81"
down_revision: str | Sequence[str] | None = "3737c72ff7ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_page_result_scan_run_id"), table_name="page_result")
    op.create_index("ix_page_result_scan_run_id_id", "page_result", ["scan_run_id", "id"], unique=False)
    op.drop_index(op.f("ix_rule_finding_page_result_id"), table_name="rule_finding")
    op.create_index("ix_rule_finding_page_result_id_type", "rule_finding", ["page_result_id", "type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rule_finding_page_result_id_type", table_name="rule_finding")
    op.create_index(op.f("ix_rule_finding_page_result_id"), "rule_finding", ["page_result_id"], unique=False)
    op.drop_index("ix_page_result_scan_run_id_id", table_name="page_result")
    op.create_index(op.f("ix_page_result_scan_run_id"), "page_result", ["scan_run_id"], unique=False)
    # ### end Alembic commands ###
