"""add brand_id to score_snapshot

Revision ID: c6db486866ba
Revises: c3d5073dbe98
Create Date: 2026-04-11 21:14:43.301008

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6db486866ba"
down_revision: str | Sequence[str] | None = "c3d5073dbe98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("score_snapshot", sa.Column("brand_id", sa.BigInteger(), nullable=True))
    op.create_index("ix_score_snapshot_brand_id", "score_snapshot", ["brand_id"], unique=False)
    op.create_foreign_key(
        "fk_score_snapshot_brand_id", "score_snapshot", "brand", ["brand_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_score_snapshot_brand_id", "score_snapshot", type_="foreignkey")
    op.drop_index("ix_score_snapshot_brand_id", table_name="score_snapshot")
    op.drop_column("score_snapshot", "brand_id")
    # ### end Alembic commands ###
