"""change app-owned FKs from restrict to cascade

Revision ID: cc5e604269d9
Revises: 7e86bd2f1537
Create Date: 2026-04-12 10:11:06.517516

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc5e604269d9"
down_revision: str | Sequence[str] | None = "7e86bd2f1537"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("page_result_scan_run_id_fkey"), "page_result", type_="foreignkey")
    op.create_foreign_key(
        op.f("page_result_scan_run_id_fkey"), "page_result", "scan_run", ["scan_run_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("scan_run_app_id_fkey"), "scan_run", type_="foreignkey")
    op.create_foreign_key(op.f("scan_run_app_id_fkey"), "scan_run", "app", ["app_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("score_snapshot_app_id_fkey"), "score_snapshot", type_="foreignkey")
    op.drop_constraint(op.f("score_snapshot_scan_run_id_fkey"), "score_snapshot", type_="foreignkey")
    op.create_foreign_key(
        op.f("score_snapshot_app_id_fkey"), "score_snapshot", "app", ["app_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        op.f("score_snapshot_scan_run_id_fkey"),
        "score_snapshot",
        "scan_run",
        ["scan_run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("score_snapshot_scan_run_id_fkey"), "score_snapshot", type_="foreignkey")
    op.drop_constraint(op.f("score_snapshot_app_id_fkey"), "score_snapshot", type_="foreignkey")
    op.create_foreign_key(
        op.f("score_snapshot_scan_run_id_fkey"),
        "score_snapshot",
        "scan_run",
        ["scan_run_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("score_snapshot_app_id_fkey"), "score_snapshot", "app", ["app_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint(op.f("scan_run_app_id_fkey"), "scan_run", type_="foreignkey")
    op.create_foreign_key(op.f("scan_run_app_id_fkey"), "scan_run", "app", ["app_id"], ["id"], ondelete="RESTRICT")
    op.drop_constraint(op.f("page_result_scan_run_id_fkey"), "page_result", type_="foreignkey")
    op.create_foreign_key(
        op.f("page_result_scan_run_id_fkey"), "page_result", "scan_run", ["scan_run_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###
