"""use text with check constraint and index parent_id

Revision ID: dc4ced6bb712
Revises: 370cb9cfe3bd
Create Date: 2026-04-09 02:35:53.714179

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc4ced6bb712"
down_revision: str | Sequence[str] | None = "370cb9cfe3bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("org_unit", "name", existing_type=sa.VARCHAR(length=255), type_=sa.Text(), existing_nullable=False)
    op.create_check_constraint("ck_org_unit_name_length", "org_unit", "LENGTH(name) <= 255")
    op.create_index("ix_org_unit_parent_id", "org_unit", ["parent_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_org_unit_parent_id", table_name="org_unit")
    op.drop_constraint("ck_org_unit_name_length", "org_unit", type_="check")
    op.alter_column("org_unit", "name", existing_type=sa.Text(), type_=sa.VARCHAR(length=255), existing_nullable=False)
    # ### end Alembic commands ###
