"""add score_snapshot table

Revision ID: f49e037fdb6e
Revises: 7eb59e13902c
Create Date: 2026-04-10 12:44:47.990773

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f49e037fdb6e"
down_revision: str | Sequence[str] | None = "7eb59e13902c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "score_snapshot",
        sa.Column("app_id", sa.BigInteger(), nullable=False),
        sa.Column("scan_run_id", sa.BigInteger(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("total_issues", sa.Integer(), nullable=False),
        sa.Column("pages_with_issues", sa.Integer(), nullable=False),
        sa.Column("pages_with_critical_issues", sa.Integer(), nullable=False),
        sa.Column("total_pages", sa.Integer(), nullable=False),
        sa.Column("avg_issues_per_page", sa.Float(), nullable=False),
        sa.Column("pct_pages_with_issues", sa.Float(), nullable=False),
        sa.Column("pct_pages_with_critical_issues", sa.Float(), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["app.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["scan_run_id"], ["scan_run.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_run_id"),
    )
    op.create_index("ix_score_snapshot_app_id", "score_snapshot", ["app_id"], unique=False)
    op.create_index("ix_score_snapshot_scan_run_id", "score_snapshot", ["scan_run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_score_snapshot_scan_run_id", table_name="score_snapshot")
    op.drop_index("ix_score_snapshot_app_id", table_name="score_snapshot")
    op.drop_table("score_snapshot")
    # ### end Alembic commands ###
